[project]
name = "spark-data-analysis"
version = "0.1.0"
authors = [{ name = "Eduard Occhipinti" }, { name = "Domenico di Stasio" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyspark<4.0.0",   # Spark 4 slightly breaks the regex syntax for reading multiple CSV files
    "kafka-python-ng",
    "rich",
    "pandas",
    "matplotlib",
    "numpy",
    "typst",
    "retry"
]

[project.optional-dependencies]
dev = [
    "pip-tools", # Provides pip-compile
    "sphinx",    # Documentation generator
]

[tool.setuptools]
py-modules = []
